# All Regression Together
- Here we will perform all the regression together to see which regression model is best for our data.

# Mulitple Linear Regression
**Importing the Libraries**

In [1]:
# Numpy allows us to work with array.
import numpy as np

# Maptplotlib which allows us to plot some chart.
import matplotlib.pyplot as plt

# Pandas allows us to not only import the datasets but also create the matrix of features(independent) and 
# dependent variable.
import pandas as pd

**Importing the dataset**

- The independent variable usally in the first columns of dataset and dependent variable usally in the last columns of the data sets.
- X is Independent Variable.
- Y is Dependent Variable.

In [2]:
dataset = pd.read_csv('Combined_Cycle _Powerplant.csv')
x1 = dataset.iloc[:, :-1].values
y1 = dataset.iloc[:, -1].values

**Splitting the dataset into the Training set and Test set**

In [3]:
# Importing Package
from sklearn.model_selection import train_test_split

# Dividing training and test set.
# The best ratio is 80 - 20 for trainging and testing respectively.
x1_train, x1_test, y1_train, y1_test = train_test_split(x1, y1, test_size = 0.2, random_state = 0)

print(x1_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [4]:
print(y1_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


**Training the Multiple Linear Regression model on the Training set**

In [5]:
# Importing Package
from sklearn.linear_model import LinearRegression

reg = LinearRegression()

# Fitting the model
reg.fit(x1_train, y1_train)

LinearRegression()

**Predicting the Test set results**

In [6]:
# Predicting
y1_pred =  reg.predict(x1_test)

# Getting only 2 decimal
np.set_printoptions(precision = 2)

# Concatenating and Reshaping
print(np.concatenate((y1_pred.reshape(len(y1_pred), 1), y1_test.reshape(len(y1_test), 1)), axis = 1))

# First column is the vector prediction and Second vector is the real predication.
# As we can see, prediction are very close.

[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


**Evaluating the Model Preformance**

In [7]:
# Importing Package
from sklearn.metrics import r2_score

# R-squared Coefficient
print("R Squared Coefficient of Multiple Linear Regression is",r2_score(y1_test, y1_pred))

R Squared Coefficient of Multiple Linear Regression is 0.9325315554761302


# Polynomial Linear Regression

**Importing the dataset**

In [8]:
dataset = pd.read_csv('Combined_Cycle _Powerplant.csv')
x2 = dataset.iloc[:, :-1].values
y2 = dataset.iloc[:, -1].values

**Splitting the dataset into the Training set and Test set**

In [9]:
# Importing Package
from sklearn.model_selection import train_test_split

# Dividing training and test set.
# The best ratio is 80 - 20 for trainging and testing respectively.
x2_train, x2_test, y2_train, y2_test = train_test_split(x2, y2, test_size = 0.2, random_state = 0)

print(x2_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [10]:
print(y2_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


**Training the Polynomial Linear Regression model on the Training set**

In [11]:
# Importing Package
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

# Tranforming Matrix
poly_reg = PolynomialFeatures(degree = 4)
x2_poly = poly_reg.fit_transform(x2_train)

# Polynomial Model
regressor = LinearRegression()
regressor.fit(x2_poly, y2_train)

LinearRegression()

**Predicting the Test set results**

In [12]:
# Predicting Regression
y2_pred = regressor.predict(poly_reg.transform(x2_test))
np.set_printoptions(precision=2)

# Concatenating and reshaping
print(np.concatenate((y2_pred.reshape(len(y2_pred),1), y2_test.reshape(len(y2_test),1)),1))

[[433.94 431.23]
 [457.9  460.01]
 [460.52 461.14]
 ...
 [469.53 473.26]
 [438.27 438.  ]
 [461.67 463.28]]


**Evaluating the Model Preformance**

In [13]:
# Importing Package
from sklearn.metrics import r2_score

# R-squared Coefficient
print("R Squared Coefficient of Polynomial Linear Regression is",r2_score(y2_test, y2_pred))

R Squared Coefficient of Polynomial Linear Regression is 0.9458193070905196


# Support Vector Regression

**Importing the dataset**

In [14]:
dataset = pd.read_csv('Combined_Cycle _Powerplant.csv')
x3 = dataset.iloc[:, :-1].values
y3 = dataset.iloc[:, -1].values

In [15]:
y3 = y3.reshape(len(y3),1)

**Splitting the dataset into the Training set and Test set**

In [16]:
# Importing Package
from sklearn.model_selection import train_test_split

# Dividing training and test set.
# The best ratio is 80 - 20 for trainging and testing respectively.
x3_train, x3_test, y3_train, y3_test = train_test_split(x3, y3, test_size = 0.2, random_state = 0)

print(x3_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [17]:
print(y3_train)

[[473.93]
 [467.87]
 [431.97]
 ...
 [459.01]
 [462.72]
 [428.12]]


**Feature Scaling**

In [18]:
# Importing Package
from sklearn.preprocessing import StandardScaler

sc_x3 = StandardScaler()
sc_y3 = StandardScaler()

x3_train = sc_x3.fit_transform(x3_train)
y3_train = sc_y3.fit_transform(y3_train)

**Training the SVR model on the Training set**

In [19]:
# Importing Package
from sklearn.svm import SVR

regressor = SVR(kernel = 'rbf')

# Fitting
regressor.fit(x3_train, y3_train)

c:\users\dhairya\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVR()

**Predicting the Test set results**

In [20]:
# Predicting 
y3_pred = sc_y3.inverse_transform(regressor.predict(sc_x3.transform(x3_test)))

np.set_printoptions(precision=2)

# Concatenating and Reshaping
print(np.concatenate((y3_pred.reshape(len(y3_pred),1), y3_test.reshape(len(y3_test),1)),1))

[[434.05 431.23]
 [457.94 460.01]
 [461.03 461.14]
 ...
 [470.6  473.26]
 [439.42 438.  ]
 [460.92 463.28]]


**Evaluating the Model Performance**

In [21]:
# Importing Package
from sklearn.metrics import r2_score

# R-squared Coefficient
print("R Squared Coefficient of Support Vector Regression is",r2_score(y3_test, y3_pred))

R Squared Coefficient of Support Vector Regression is 0.9480784049986258


# Decision Tree Regression

**Importing the dataset**

In [22]:
dataset = pd.read_csv('Combined_Cycle _Powerplant.csv')
x4 = dataset.iloc[:, :-1].values
y4 = dataset.iloc[:, -1].values

**Splitting the dataset into the Training set and Test set**

In [23]:
# Importing Package
from sklearn.model_selection import train_test_split

# Dividing training and test set.
# The best ratio is 80 - 20 for trainging and testing respectively.
x4_train, x4_test, y4_train, y4_test = train_test_split(x4, y4, test_size = 0.2, random_state = 0)

print(x4_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [24]:
print(y4_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


**Training the Decision Tree Regression model on the Training set**

In [25]:
# Importing Package
from sklearn.tree import DecisionTreeRegressor

regressor = DecisionTreeRegressor(random_state = 0)

# Fitting
regressor.fit(x4_train, y4_train)

DecisionTreeRegressor(random_state=0)

**Predicting the Test set results**

In [26]:
# Prediction
y4_pred = regressor.predict(x4_test)
np.set_printoptions(precision=2)

# Concatenating and Reshaping
print(np.concatenate((y4_pred.reshape(len(y4_pred),1), y4_test.reshape(len(y4_test),1)),1))

[[431.28 431.23]
 [459.59 460.01]
 [460.06 461.14]
 ...
 [471.46 473.26]
 [437.76 438.  ]
 [462.74 463.28]]


**Evaluating the Model Performance**

In [27]:
# Importing Package
from sklearn.metrics import r2_score

# R-squared Coefficient
print("R Squared Coefficient of Decision Tree Regression is",r2_score(y4_test, y4_pred))

R Squared Coefficient of Decision Tree Regression is 0.922905874177941


# Random Forest Regression

**Importing the dataset**

In [28]:
dataset = pd.read_csv('Combined_Cycle _Powerplant.csv')
x5 = dataset.iloc[:, :-1].values
y5 = dataset.iloc[:, -1].values

**Splitting the dataset into the Training set and Test set**

In [29]:
# Importing Package
from sklearn.model_selection import train_test_split

# Dividing training and test set.
# The best ratio is 80 - 20 for trainging and testing respectively.
x5_train, x5_test, y5_train, y5_test = train_test_split(x5, y5, test_size = 0.2, random_state = 0)

print(x5_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [30]:
print(y5_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


**Training the Random Forest Regression model on the whole dataset**

In [31]:
# Importing Package
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)

# Fitting
regressor.fit(x5_train, y5_train)

RandomForestRegressor(n_estimators=10, random_state=0)

**Predicting the Test set results**

In [32]:
# Predicting
y5_pred = regressor.predict(x5_test)
np.set_printoptions(precision=2)

# Concatenating and Reshaping
print(np.concatenate((y5_pred.reshape(len(y5_pred),1), y5_test.reshape(len(y5_test),1)),1))

[[434.05 431.23]
 [458.79 460.01]
 [463.02 461.14]
 ...
 [469.48 473.26]
 [439.57 438.  ]
 [460.38 463.28]]


**Evaluating the Model Performance**

In [33]:
# Importing Package
from sklearn.metrics import r2_score

# R-squared Coefficient
print("R Squared Coefficient of Random Forest Regression is",r2_score(y5_test, y5_pred))

R Squared Coefficient of Random Forest Regression is 0.9615908334363876


**Final Result**

In [36]:
print("R Squared Coefficient of Multiple Linear Regression is",r2_score(y1_test, y1_pred))
print("R Squared Coefficient of Polynomial Linear Regression is",r2_score(y2_test, y2_pred))
print("R Squared Coefficient of Support Vector Regression is",r2_score(y3_test, y3_pred))
print("R Squared Coefficient of Decision Tree Regression is",r2_score(y4_test, y4_pred))
print("R Squared Coefficient of Random Forest Regression is",r2_score(y5_test, y5_pred))

R Squared Coefficient of Multiple Linear Regression is 0.9325315554761302
R Squared Coefficient of Polynomial Linear Regression is 0.9458193070905196
R Squared Coefficient of Support Vector Regression is 0.9480784049986258
R Squared Coefficient of Decision Tree Regression is 0.922905874177941
R Squared Coefficient of Random Forest Regression is 0.9615908334363876


## So the best model for our data is Random Forest Regression.